# ./docker-compose.yml

version: '3'

services:
  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./:/usr/src/app
  #     - /usr/src/app/node_modules
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - app-network
  #   depends_on:
  #     - messages_db

  messages_db:
    image: mysql:5.7
    container_name: messages_db
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_pw_shh
      MYSQL_DATABASE: messanger
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge